### PR TITLE
Fix for #20 (request headers not retained on redirect)

### LINKED ISSUE #20: Request Headers are not preserved on redirects
I've got a client configured with DefaultRequestHeaders (accept, etc, not authorization headers). It looks like a new request is being created for redirects and the headers are not being copied across.

### PR DESCRIPTION
**Pull request by nukefusion**
This pull request fixes #20

### CODE REVIEW

File: src/OwinHttpMessageHandler/OwinHttpMessageHandler.cs [hunk 1]
```diff
@@ -185,7 +185,9 @@ public CookieContainer CookieContainer
                 }
 
                 var redirectMethod = IsRedirectToGet(statusCode) ? HttpMethod.Get : request.Method;
-                request = new HttpRequestMessage(redirectMethod, location);
+                request.RequestUri = location;
+                request.Method = redirectMethod;
```
Comment (damianh) [inline src/OwinHttpMessageHandler/OwinHttpMessageHandler.cs]: @nukefusion Just to be sure, is it safe to mutate and reuse a `HttpRequestMessage` like this? I think I read somewhere it can only be used for one request...

File: src/OwinHttpMessageHandler.Tests/AutoRedirectTests.cs [hunk 2]
```diff
@@ -93,6 +94,27 @@ public AutoRedirectTests()
             }
         }
 
+        [Theory]
+        [InlineData("Accept", "application/json")]
+        [InlineData("Accept-Charset", "utf-8")]
+        [InlineData("Accept-Encoding", "gzip, deflate")]
+        [InlineData("Cache-Control", "no-cache")]
+        [InlineData("User-Agent", "Mozilla/5.0 (X11; Linux x86_64; rv:12.0) Gecko/20100101 Firefox/21.0")]
```
Comment (damianh) [inline src/OwinHttpMessageHandler.Tests/AutoRedirectTests.cs]: 🤔 Are there any headers that _shouldn't_ be copied in a redirect. According to this http://stackoverflow.com/a/1969728 just cookies. Hmmm

Comment (damianh) [inline src/OwinHttpMessageHandler.Tests/AutoRedirectTests.cs]: According to this http://stackoverflow.com/a/4696017 and http://blog.dubbelboer.com/2012/11/25/302-cookie.html I think we should handle cookie sets before issuing the redirected request. 

Thoughts?

File: src/OwinHttpMessageHandler/OwinHttpMessageHandler.cs (hunk 1 above)
Comment (nukefusion) [inline src/OwinHttpMessageHandler/OwinHttpMessageHandler.cs]: I know that HttpClient prevents you from sending the same request object twice. Each time SendAsync is called on HttpClient the request message is checked via a counter at this line.
However, since we are re-dispatching the request inside of the handler we aren't bound by that restriction.

I'm not aware of any other reason why we couldn't reuse it, as long as it's in a valid state.

File: src/OwinHttpMessageHandler.Tests/AutoRedirectTests.cs (hunk 2 above)
Comment (nukefusion) [inline src/OwinHttpMessageHandler.Tests/AutoRedirectTests.cs]: I know that a lot of web client implementations strip out Authorization headers on redirects for reasons of security. Not sure if it's relevant for the purposes of this handler though? Are cookie sets not already handled by the existing code?

Comment (damianh) [inline src/OwinHttpMessageHandler.Tests/AutoRedirectTests.cs]: > Not sure if it's relevant for the purposes of this handler though?

Yes it's relevant for this handler. We should add that.

> Are cookie sets not already handled by the existing code?

No, I've added it with tests to your code:
https://github.com/damianh/OwinHttpMessageHandler/commit/f65f90819d50fff3ca97fba7b865aefce0361fce#diff-23eabb4c1a9ac5b009c6ec8942690ab9R190

Comment (damianh) [inline src/OwinHttpMessageHandler.Tests/AutoRedirectTests.cs]: Authorization header being removed https://github.com/damianh/OwinHttpMessageHandler/commit/356414a8d62cc511e63e2ec5a71697317c489873

File: src/OwinHttpMessageHandler/OwinHttpMessageHandler.cs (hunk 1 above)
Comment (damianh) [inline src/OwinHttpMessageHandler/OwinHttpMessageHandler.cs]: Thinking out loud: If the server reads the request stream and _then_ responds with a redirect, the stream is not usable if it cannot seek back to beginning. (GETs can contain a request body)

Comment (damianh) [inline src/OwinHttpMessageHandler/OwinHttpMessageHandler.cs]: This is most likely a concern for `307` where one should re-issue the `POST` requests.

Comment (damianh) [inline src/OwinHttpMessageHandler/OwinHttpMessageHandler.cs]: @pmhsfelix I would appreciate your thoughts on this.

Comment (damianh) [inline src/OwinHttpMessageHandler/OwinHttpMessageHandler.cs]: Actually scratch that; if redirects only followed if "bodyless".
